services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    env_file:
      - ./user-service/.env
    depends_on:
      - mongo
      - rabbitmq

  review-service:
    build: ./review-service
    ports:
      - "5001:5001"
    env_file:
      - ./review-service/.env
    depends_on:
      - mongo 
      - rabbitmq
      - user-service

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mongo-data:
  rabbitmq-data:
